blank_issues_enabled: true
contact_links:
  - name: Documentation 
    url: https://iroiro.dev/SwiftStorage/documentation/swiftstorage/
    about: More information on using SwiftStorage can be found here.